name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.16.1]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.16.1
    - run: npm install
    - run: npm run build --if-present
      env:
        CI: true
  sonar:
    name: sonar
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SonarCloud
        uses: SonarSource/sonarcloud-github-action@v1.1
        env:
          SONAR_TOKEN: $ {{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: $ {{ secrets.GITHUB_TOKEN }}
          SONAR.ORGANIZATION: ala-benkhlifa
          SONAR.PROJECTKEY: ala-benkhlifa_internship-ui
          SONAR.SOURCES: .
          SONAR.HOST.URL: https://sonarcloud.io
          SONAR.LOGIN: $ {{ secrets.SONAR_LOGIN }}
          SONAR.PASSWORD: $ {{ secrets.SONAR_PASS }}
          
